name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install deps
        run: |
          pip install -r python/requirements.txt || true
      - name: Lint structure
        run: |
          test -f README.md && echo OK
          test -d python/app && echo OK

